### ISSUE TITLE
啟動不了ES: models.es_jobbole.py

### ISSUE THREAD

**Issue by Paw2Pom** [mtianyan/ArticleSpider#3]
我試者執行es pipeline, 但我發現es沒有先生成index, 所以我去跑了model裡的es_jobbole.py:

python es_jobbole.py

以下error產生了:

=====

PUT http://192.168.1.129:9200/jobbole [status:400 request:0.007s]
Traceback (most recent call last):
  File "es_jobbole.py", line 48, in <module>
    ArticleType.init()
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch_dsl/document.py", line 147, in init
    cls._doc_type.init(index, using)
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch_dsl/document.py", line 94, in init
    self.mapping.save(index or self.index, using=using or self.using)
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch_dsl/mapping.py", line 79, in save
    return index.save()
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch_dsl/index.py", line 195, in save
    return self.create()
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch_dsl/index.py", line 179, in create
    self.connection.indices.create(index=self._name, body=self.to_dict(), **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/client/indices.py", line 107, in create
    params=params, body=body)
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/connection/http_urllib3.py", line 128, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/connection/base.py", line 124, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, 'mapper_parsing_exception', 'analyzer [ik_max_word] not found for field [title]')

**Comment by Paw2Pom** [comment]
請問是用哪一個版本的elasticsearch? Requirement.txt裡面的packages是用哪些版本呢?

**Comment by mtianyan** [comment]
@Paw2Pom  使用的是elasticSearch-rtf 中文发行版。requirements.txt一会传上来

**Comment by Paw2Pom** [comment]
感謝, 但我還是沒辦法寫入elasticsearch index. 我用的是docker elasticsearch/kibana v5.6.7.

**Comment by Paw2Pom** [comment]
我想環境用docker-compose架起來可能比較好裝

**Comment by mtianyan** [comment]
@Paw2Pom elasticSearch-rtf 是一个集成了很多中文插件的版本，里面很多插件都在项目里用到了，为初学者免去很多烦恼。建议直接下载该版本，对应的Kibana也应下载对应5.1.1的版本。最近还没有docker化的计划。如果你有意向做一个分享出来，可以加有趣的python 619417153

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video
